name: freerasp_brick_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  file: ^6.1.4
  mason: ^0.1.0-dev
  xml_parser: ^1.0.0

dev_dependencies:
  test: ^1.22.0
  very_good_analysis: ^3.1.0
