name: Very Good Workflow

on:
  pull_request:
    paths:
      - ".github/workflows/brick_workflow.yaml"
      - "hooks/**"
      - "hooks/test/**"
      - "hooks/pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/brick_workflow.yaml"
      - "hooks/**"
      - "hooks/test/**"
      - "hooks/pubspec.yaml"

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hooks

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: |
          dart pub global activate coverage 1.3.0
          dart test --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
